In [1]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
lbl= LabelEncoder()
enc = OneHotEncoder()
qualitative =["red", "red", "green", "blue","orange","blue","blue", "orange", "green","red"]
labels = lbl.fit_transform(qualitative).reshape(10,1)
print(enc.fit_transform(labels).toarray())

[[0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]
