**One-Hot Encoding**
Each feature contains zero values, unless its class appears in the data, when it takes a value of one. 

In [1]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
lbl= LabelEncoder()
enc = OneHotEncoder()
qualitative =["red", "red", "green", "blue","orange","blue","blue", "orange", "green","red"]
labels = lbl.fit_transform(qualitative).reshape(10,1)
print(enc.fit_transform(labels).toarray())

[[0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]


**Binary Response**
Coding a response vector as a sequence of positive and negative values. 

In [1]:
import numpy as np

a=np.array([0,0,0,0,1,1,1,1])
b=np.array([1,2,3,4,5,6,7,8]).reshape(8,1)
from sklearn.linear_model import LinearRegression
regression = LinearRegression()
regression.fit(b,a)
print(regression.predict(b)>.5)



[False False False False  True  True  True  True]
